export default  {
    products: [
        {
            id: 1,
            name: 'Jordan 1 Retro High Satin Snake Chicago (W)',
            brand: 'NIKE',
            price: 4500,
            rating: 4.5,
            numStock: 100,
            numReview: 10,
            image: '/images/nike1.jpg'
        },
        {
            id: 2,
            name: 'Nike Air Max 97 Neon Seoul',
            brand: 'NIKE',
            price: 4800,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike2.jpg'
        },
        {
            id: 3,
            name: 'Nike Air Max 97 Black Blue Nebula',
            brand: 'NIKE',
            price: 4000,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike3.jpg'
        },
        {id: 4,
            name: 'Nike Air Force 1 Low Off-White Black White',
            brand: 'NIKE',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike4.jpg'
        },
        {id: 5,
            name: 'adidas Yeezy Boost 350 V2 Zebra',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/adidas1.jpg'
        },
        {id: 6,
            name: 'adidas Yeezy Boost 350 V2 Cinder',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/adidas2.jpg'
        },
        {id: 7,
            name: 'Jordan 1 Retro High Clay Green',
            brand: 'NIKE',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike6.jpg'
        },
        {id: 8,
            name: 'Jordan 1 Retro High Royal Toe',
            brand: 'NIKE',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/jordan1.jpg'
        },
        {id: 9,
            name: 'adidas Equipment Running Guidance Black',
            brand: 'ADIDAS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/adidas3.jpg'
        },
        {id: 10,
            name: 'Nike Air Force 1 Low Travis Scott Cactus Jack',
            brand: 'NIKE',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/nike5.jpg'
        },
        {id: 11,
            name: 'Puma RS-Dreamer J. Cole Black',
            brand: 'PUMA',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/puma1.jpg'
        },
        {id: 12,
            name: 'ASICS Gel-Lyte III Ronnie Fieg Militia (Special Box)',
            brand: 'ASICS',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/asics1.jpg'
        },
        {id: 13,
            name: 'Balenciaga Triple S Grey Red Blue (2018 Reissue)',
            brand: 'Balenciaga',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Balenciaga1.jpg'
        },
        {id: 14,
            name: 'Converse Chuck Taylor All-Star 70s Ox Kith x Coca Cola Red',
            brand: 'Converse',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Converse1.jpg'
        },
        {id: 15,
            name: 'New Balance 327 Concepts Cape',
            brand: 'New balance',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/New Balance1.jpg'
        },
        {id: 16,
            name: 'Reebok Instapump Fury CNCPTS Versace',
            brand: 'Reebok',
            price: 3500,
            rating: 3.5,
            numStock: 50,
            numReview: 20, 
            image: '/images/Reebok1.jpg'
        }
    ]
}



